# Generated by Django 3.0.1 on 2020-02-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('total_amt', models.IntegerField()),
                ('bank_acc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('email', models.EmailField(max_length=254)),
                ('distribute_catagory', models.BooleanField(default=False)),
                ('distribute_amt', models.IntegerField()),
                ('receiver_acc', models.IntegerField()),
                ('distribute_handcash', models.IntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Org')),
            ],
        ),
        migrations.CreateModel(
            name='ChildEduDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('address', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(verbose_name=10)),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('donate_catagory', models.CharField(max_length=50)),
                ('donate_amt', models.IntegerField()),
                ('comments', models.CharField(max_length=300)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Org')),
            ],
        ),
    ]
